twig:
    paths:
        "%kernel.project_dir%/vendor/green-symfony/generic-parts-bundle/Resources":        GSGenericPartsResources
        "%kernel.project_dir%/vendor/green-symfony/generic-parts-bundle/Resources/views":  GSGenericParts