twig:
    paths:
        "%kernel.project_dir%/vendor/green-symfony/generic-parts/Resources":        GSGenericPartsResources
        "%kernel.project_dir%/vendor/green-symfony/generic-parts/Resources/views":  GSGenericParts