parameters:
    gs_generic_parts.timezone:                          'UTC'
    gs_generic_parts.timezone_session_name:             'gs_generic_parts.tz_session_name'
    gs_generic_parts.locale:                            'en'
        
services:
    _defaults:
        autowire:           true
        autoconfigure:      true
        #bind: # only for these services
    
    ###> TEST SERVICE ###
    gs_generic_parts.test_service:
        autoconfigure:          false
        autowire:               false
        public:                 false
        class:                  GS\GenericParts\Service\TestService
    ###< TEST SERVICE ###
    
    
    ###> CONTROLLERS ###
    GS\GenericParts\Controller\ApiUtcDtController:
        autoconfigure:          false
        autowire:               false
        public:                 true
        class:                  GS\GenericParts\Controller\ApiUtcDtController
        arguments:
            $tzSessionName:     '%gs_generic_parts.timezone_session_name%'
    
    GS\GenericParts\Controller\ApiSetTimezoneController:
        autoconfigure:          false
        autowire:               false
        public:                 true
        class:                  GS\GenericParts\Controller\ApiSetTimezoneController
        arguments:
            $tzSessionName:     '%gs_generic_parts.timezone_session_name%'
    ###< CONTROLLERS ###
    
    
    ###> API SERVICES ###
    ###> CARBON ###
    gs_generic_parts.carbon_factory_ru_RU_UTC:
        autoconfigure:          false
        autowire:               false
        public:                 true
        class:                  Carbon\FactoryImmutable
        arguments:
        -   locale:                   '%gs_generic_parts.locale%'
            strictMode:               true
            timezone:                 '%gs_generic_parts.timezone%'
            toStringFormat:           'd.m.Y H:i:s P'
            monthOverflow:            true # addXXX add(<>, <>)
            yearOverflow:             true        
    ###< CARBON ###
    
    ###> FAKER ###
    gs_generic_parts.faker:
        autoconfigure:          false
        autowire:               false
        public:                 true
        class:                  Faker\Factory
        factory:        ['Faker\Factory', 'create']
        arguments:
            - '%gs_generic_parts.locale%'
    ###< FAKER ###
    
    ###> MESSENGER ###
    ###> A handy way to get result of a sync message | $result = $thisService(new Message) ###
    gs_generic_parts.sync_message:
        autoconfigure:          true
        autowire:               false
        public:                 true
        class:                  GS\GenericParts\Messenger\SyncMessage
        arguments:
            $messageBus:    '@Symfony\Component\Messenger\MessageBusInterface'
    ###< MESSENGER ###
    ###< API SERVICES ###
    
    
    ###> KERNEL SUBSCRIBER ###
    gs_generic_parts.init_subscriber:
        autoconfigure:          true
        autowire:               false
        public:                 false
        class:                  GS\GenericParts\EventSubscriber\InitSubscriber
        arguments:
            $defaultTimeZone:           '%gs_generic_parts.timezone%'
            $bus:                       '@Symfony\Component\Messenger\MessageBusInterface'
    ###< KERNEL SUBSCRIBER ###
    
    
    ###> TWIG ###
    ###> COMPONENT ###  
    GS\GenericParts\Twig\Component\GSAlertComponent:
        class:                  GS\GenericParts\Twig\Component\GSAlertComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
    GS\GenericParts\Twig\Component\GSDtComponent:
        class:                  GS\GenericParts\Twig\Component\GSDtComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
        arguments:
            $carFacImm:         '@gs_generic_parts.carbon_factory_ru_RU_UTC' 
    GS\GenericParts\Twig\Component\GSNavsComponent:
        class:                  GS\GenericParts\Twig\Component\GSNavsComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
    GS\GenericParts\Twig\Component\GSSpriteComponent:
        class:                  GS\GenericParts\Twig\Component\GSSpriteComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
    GS\GenericParts\Twig\Component\GSSubmitButtonComponent:
        class:                  GS\GenericParts\Twig\Component\GSSubmitButtonComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
    GS\GenericParts\Twig\Component\GSWatchComponent:
        class:                  GS\GenericParts\Twig\Component\GSWatchComponent
        autoconfigure:          true
        autowire:               false
        public:                 false
    
    ###> EXTENSION ###
    GS\GenericParts\Twig\Extension\ByteForHumansExtension:
        class:                  GS\GenericParts\Twig\Extension\ByteForHumansExtension
        autoconfigure:          true
        autowire:               false
        public:                 false
    GS\GenericParts\Twig\Extension\DefaultExtension:
        class:                  GS\GenericParts\Twig\Extension\DefaultExtension
        autoconfigure:          true
        autowire:               false
        public:                 false
        arguments:
            $faker:             '@gs_generic_parts.faker'
            $carFacImm:         '@gs_generic_parts.carbon_factory_ru_RU_UTC'
            $formFactory:       '@Symfony\Component\Form\FormFactoryInterface'
    ###< TWIG ###
    
    
    ###> MESSENGER ###
    ###> HANDLERS ###
    gs_generic_parts.init_carbon_handler:
        class:                  GS\GenericParts\Messenger\KernelBootstrap\Command\Handler\InitCarbonHandler
        autoconfigure:          true
        autowire:               false
        public:                 false
        arguments:
            $defaultLocale: '%gs_generic_parts.locale%'
    
    GS\GenericParts\Messenger\KernelBootstrap\Command\Handler\SetDefaultDateTimeZoneHandler:
        class:                  GS\GenericParts\Messenger\KernelBootstrap\Command\Handler\SetDefaultDateTimeZoneHandler
        autoconfigure:          true
        autowire:               false
        public:                 false
    ###< HANDLERS ###
    ###< MESSENGER ###